config/routes.rb
Rails.application.routes.draw do
  root 'inquiries#new'
  post 'inquiries/confirm'
  post 'inquiries/thanks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true, length: { in: 1..160 }
  validates :email, presence: true
  validates :content, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new;
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      render "confirm"
    else
      render :new
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver_now
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :relationship, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/confirm.html.erb
<div class="confirmPage">
  <div class='container'>
    <h1 class="confirmPage_title">通報内容</h1>
    <%= form_with model: @inquiry, url: inquiries_thanks_path, method: :post, local: true do |f| %>
      <div class="confirmForm_item">
        <h3>鼻毛が出ている人のお名前</h3>
        <div>
          <%= f.hidden_field :name %>
          <%= @inquiry.name %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>鼻毛が出ている人のメールアドレス</h3>
        <div>
          <%= f.hidden_field :email %>
          <%= @inquiry.email %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>鼻毛が出ている人との関係</h3>
        <div>
          <%= f.hidden_field :relationship %>
          <%= @inquiry.relationship %>
        </div>
      </div>
      <div class="confirmForm_item">
        <h3>何か伝えたいこと</h3>
        <div>
          <% if @inquiry.content.empty? %>
           特になし
          <% else %>
           <%= @inquiry.content %>
          <% end%>
          <%= f.hidden_field :content %>
        </div>
      </div>
      <div class="text-center">
        <%= link_to "入力画面に戻る", root_path, class: "btn btn-info"%>
        <%= f.submit '送信する', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/inquiries/new.html.erb
<div class='topPage'>
  <div class="container">
    <h1>鼻毛出てるよ通報代理サービス</h1>
    <p>あなたの周りにいる方の”鼻毛が出ていたら"気軽に「鼻毛が出ているよ？」といえるでしょうか？そんな方の代理をいたします。
    </p>
    <%= form_with(model: @inquiry, url: inquiries_confirm_path, local: true) do |f| %>
    <% if @inquiry.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <strong>入力内容にエラーがあります</strong>
        <ul>
          <% @inquiry.errors.each do |attr, msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="form-group">
       <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "お名前" %>
      </div>
      <div class="form-group">
       <%= f.label :email %>
        <%= f.text_field :email, autofocus: true, class: "form-control", placeholder: "メールアドレス" %>
      </div>
      <div class="form-group">
        <%= f.label :relationship %>
        <%= f.select(:relationship, [["同僚", "同僚"], ["先輩", "先輩"], ["後輩", "後輩"], ["同じ部署の者です", "同じ部署の者です"], ["違う部署の者です", "違う部署の者です"]], {}, class: "form-control") %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control", placeholder: "合わせて伝えたいことがあれば入力してください" %>
      </div>
       <div class="text-center"><%= f.submit '確認画面へ', class: 'btn btn-primary' %></div>
    <% end %>
  </div>
</div>

app/views/inquiries/thanks.html.erb
<div class='thanksPage'>
  <div class='container'>
    <p class="thanksPage_message">通報いただきありがとうございました。</p>
    <div class="text-center"><%= link_to "トップへ戻る", root_path, class: "btn btn-primary" %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hanage-Deteruyo</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>